<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.9" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.9" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.9">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Jinobald.Avalonia" Version="1.0.1" />
    <PackageReference Include="Jinobald.Core" Version="1.0.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="app.manifest" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="src\Views\ChatView.axaml" />
    <AdditionalFiles Include="src\Views\HomeView.axaml" />
    <AdditionalFiles Include="src\Views\WorkspaceListView.axaml" />
    <AdditionalFiles Include="src\Views\WorkspaceView.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\App.axaml.cs">
      <DependentUpon>App.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="src\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
</Project>
